const NotificationsActionTypes = {
  GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
  GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
  UPDATE_NOTIFICATIONS: 'UPDATE_NOTIFICATIONS',
};

export default NotificationsActionTypes;
