const FollowerActionTypes = {
  ADD_FOLLOWER: 'ADD_FOLLOWER',
  // ADD_FOLLOWER_SUCCESS: 'ADD_FOLLOWER_SUCCESS',
  REMOVE_FOLLOWER: 'REMOVE_FOLLOWER',
  // REMOVE_FOLLOWER_SUCCESS: 'REMOVE_FOLLOWER_SUCCESS',
  GET_FOLLOWERS: 'GET_FOLLOWERS',
  GET_FOLLOWERS_SUCCESS: 'GET_FOLLOWERS_SUCCESS',
  GET_FOLLOWINGS: 'GET_FOLLOWINGS',
  GET_FOLLOWINGS_SUCCESS: 'GET_FOLLOWINGS_SUCCESS',
  GET_FOLLOW_SUGGESTIONS: 'GET_FOLLOW_SUGGESTIONS',
  GET_FOLLOW_SUGGESTIONS_SUCCESS: 'GET_FOLLOW_SUGGESTIONS_SUCCESS'
};

export default FollowerActionTypes;
